// Generated by Wrangler by running `wrangler types`
declare namespace Cloudflare {
  interface Env {
    OAUTH_KV: KVNamespace;
    ASSETS: Fetcher;
    SUPERTHREAD_PAT: string;
  }
}
interface Env extends Cloudflare.Env {}